<?php
echo ""
. "<div id='footser-end' class='navbar-inverse'>\n"
. "            <div>\n"
. "                  &copy; 2016 Wizzard Technologies, Inc. | <a href='index.php' class='text-info'>elecsys.com</a>\n"
. "            </div>\n"
. "            <div>\n"
. "                Web Template:\n"
. "                <a href='http://www.binarytheme.com/' class='text-info' target='_blank' >binarytheme.com</a>\n"
. "            </div>\n"
. "              <div>\n"
. "                Demo Images:\n"
. "                <a href='https://unsplash.com//' class='text-info' target='_blank' >unsplash.com</a>\n"
. "            </div>\n"
. "        </div>\n"
. "        <!-- End -->\n\n"
. "        <!-- Scripts -->\n"
. "        <script src='assets/js/jquery-1.10.2.js'></script>\n"
. "        <script src='assets/js/bootstrap.js'></script>\n"
. "        <script src='assets/js/wow.min.js'></script>\n"
. "        <script src='assets/js/jquery.easing.min.js'></script>\n"
. "        <script src='assets/js/jquery.prettyPhoto.js'></script>\n"
. "        <script src='assets/js/custom.js'></script>\n";
?>