<?php
echo ""
. "<link rel='shortcut icon' href='static/ico.ico'>\n"
. "        <meta http-equiv='Content-Type' content='text/html; charset=utf-8'/>\n"
. "        <meta name='viewport' content='width=device-width, initial-scale=1, maximum-scale=1' />\n"
. "        <meta name='description' content='' />\n"
. "        <meta name='author' content='' />\n"
. "        <!--[if IE]>\n"
. "            <meta http-equiv='X-UA-Compatible' content='IE=edge,chrome=1'>\n"
. "        <![endif]-->\n"
. "        <link href='assets/css/bootstrap.css' rel='stylesheet' />\n"
. "        <link href='assets/css/font-awesome.min.css' rel='stylesheet' />\n"
. "        <link href='assets/css/animate.css' rel='stylesheet' />\n"
. "        <link href='assets/css/prettyPhoto.css' rel='stylesheet' />\n"
. "        <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css' />\n"
. "        <link href='assets/css/style.css' rel='stylesheet' />\n"
. "        <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->\n"
. "        <!--[if lt IE 9]>\n"
. "          <script src='https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js'></script>\n"
. "          <script src='https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js'></script>\n"
. "        <![endif]-->\n";
?>